services:
  backend:
    image : anshikabansal2004/chat-backend:lts
    build:
      context: ./backend   # Path to the backend Dockerfile
    ports:
      - "8080:8080"

  backend2:
    image : anshikabansal2004/chat-backend2:lts
    build:
      context: ./backend   # Path to the backend Dockerfile
    ports:
      - "8084:8080"

  auth-backend:
    image : anshikabansal2004/chat-auth:lts
    build:
      context: ./authentication   # Path to the authentication Dockerfile
    ports:
      - "5000:5000"

  frontend:
    image : anshikabansal2004/chat-client:lts
    build:
      context: ./frontend/chatapp_ui   # Path to the frontend Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend   # Wait for backend service to be ready before starting frontend
      
  frontend2:
    image : anshikabansal2004/chat-client2:lts
    build:
      context: ./client_2/chatapp_ui   # Path to the frontend2 Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend   # Wait for backend service to be ready before starting frontend