import User from "../Models/UserModel.js";
import bcrypt from "bcrypt";
import generateJWTtokenandsetCookie from "../utils/generateJWTtoken.js";

//creating a user (signup)
const signup = async(req,res) => {
      try{
            //user created a username and pwd, we hashed the pwd:
            const{username,password} = req.body;
            const hashedPassword = await bcrypt.hash(password,10);

            //sending this new record to the DB:
            const foundUser = await User.findOne({username}); //checks if user exists in the database
            if(foundUser){
                  res.status(201).json({message: 'Username already exists. Please select a unique username'});
            }
            else{
                 const user = new User({username : username,password:hashedPassword});    
                 console.log(user);
                 await user.save(); //saving the user in the DB
                 generateJWTtokenandsetCookie(user._id,res); // 1) once user is created the jwt token is generated 
                 // _id is automatically generated by mongoDB
                 res.status(201).json({message: 'Username created!'});
            }
      }
      catch(error){
            console.log("error during signup:" + error);
            res.status(500).json({message: 'Username creation failed!'});
      }
}

// doing the login 
export const login = async(req,res) => {
      try{
            console.log("Loggin in the user");

            const{username,password} = req.body;

            //sending this new record to the DB:
            const foundUser = await User.findOne({username}); //checks if user exists in the database
            if(!foundUser){
                  res.status(401).json({message: 'Username does not exist. Please signup'});
            }
            else{
                 const passwordMatch = await bcrypt.compare(password,foundUser?.password);
                 if(!passwordMatch){
                  res.status(401).json({message: 'Incorrect password'});
                 }
                 else{
                  generateJWTtokenandsetCookie(username._id,res);
                  res.status(201).json({_id : foundUser._id,username : foundUser.username});
                 }
            }
      }
      catch(error){
            console.log("error during login:" + error);
            res.status(500).json({message: 'Username creation failed!'});
      }
}

export default signup;